export { useProformaTemplateTextListStore } from './stores/useProformaTemplateTextListStore'
export { useProformaTemplateTextFormStore } from './stores/useProformaTemplateTextFormStore'
export { useProformaTemplateTextDeleteStore } from './stores/useProformaTemplateTextDeleteStore'
export { proformaTemplateTextsService } from './services/proforma-template-texts.service'
export { TemplateTextsManager } from './ui/template-texts-manager'
export type { ProformaTemplateText } from './data/schema'
